### ISSUE TITLE
Use relative paths for attachments

### ISSUE THREAD

**Issue by marks234** [ShuiRuTian/trx-reporter-for-playwright#3]
When creating snapshots or traces these files are usually stored in [project]/test-results/[testcase]/
In the result.trx file those files are referenced as attachments with the absolute path in the current directory. If you move the test-results to another location (archive) the attachments can't be found anymore.

in trxreporter:
```
    if (attachmentPaths.length !== 0) {
      unitTestResult.ResultFiles = {
        ResultFile: attachmentPaths.map(p => ({ $path: p })),
      };
    }
```
The filenames should be relative to the trx-file. JUnit reporter does something like:
```
          const attachmentPath = path.relative(this.config.rootDir, attachment.path);
            if (fs.existsSync(attachment.path))
              systemOut.push(`\n[[ATTACHMENT|${attachmentPath}]]\n`);
            else
              systemErr.push(`\nWarning: attachment ${attachmentPath} is missing`);

```
Could this be possible in trx too?

**Comment by marks234** [comment]
I've made some further tests and it seems that relative paths won't solve the relocation problem either.

**Comment by ShuiRuTian** [comment]
Hi, could you share a bit more about the situation?

If I got it correctly, you want to move the path of the attachments to somewhere else rather than where they are generated, right?

Is it feasible to copy rather than cut the file?

I believe we could provide some hooks to change the path name of the attachments, but it's better to know more about the background.

**Comment by marks234** [comment]
Hi!
I execute the playwright tests on a container with in the K8S cluster where the SUT is running. Tests are located on the container in /e2e/tests and test results are written to /e2e/test-results. The test execution is triggered form an Azure build-agent. After executing the tests, the results are copied back to the build-agent. Then, the results are published using the PublishTestResults@2 task. This task can't find the attachments since the path in the trx-file starts with "/e2e/test-results/...".  The test-results are stored on the build agent in an arbitrary work directory. 

I solved it by replacing the absolute path in the trx file by a relative one...
`sed -i 's/<ResultFile path="\/e2e\/test-results/<ResultFile path="..\/..\/..\//g' /e2e/test-results/e2e-results.trx
`
